### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by aozorahime** [StevenChaoo/R-BERT-DDI#1]
I am just wondering where I can find the dataset? I want to reproduce your code as bert embedding. Thank you

**Comment by stevenzyzhao** [comment]
Thanks for your interest. Please find the dataset and details here (https://aclanthology.org/S13-2056.pdf). You may need to apply for approval to use this dataset :).

**Comment by aozorahime** [comment]
yes, it is XML format files. would you mind sharing your own dataset that matches with your code? I guess it is in the tsv format.

**Comment by stevenzyzhao** [comment]
I updated the program just now. Pls check the data processing folder (./DDI_Date_Create/* and ./data) for more details. But sry I cannot share the processed data with u directly.

**Comment by aozorahime** [comment]
Thank a lot for the quick response. Hope you don't mind if I contact you later when facing some troubles later.
