### ISSUE TITLE
preprocessing

### ISSUE THREAD

**Issue by aozorahime** [StevenChaoo/R-BERT-DDI#3]
Hi, sorry for disturb you again.
I am just wondering what is the purpose of enhance_marker and marker.py. I did preprocess.sh and should I do this enhance_marker afterwards?

**Comment by stevenzyzhao** [comment]
func of enhanced marker is for better representation of entity by adding entity type instead of only putting start and end around the entity word. You should put it before model training if u decide to use this. More enquiry please feel free to email me: steven.zy.zhao@outlook.com
